### ISSUE TITLE
Joining challenges could be more intuitive

### ISSUE THREAD

**Issue by LocoMortis** [veloek/spur#10]
It's also easy to leave a challenge unintentionally

**Comment by veloek** [comment]
I'm open for suggestions!

Also, if you leave a challenge unintentionally you can simply join it again and no harm is done.

**Comment by LocoMortis** [comment]
Could the Join/Leave button be permanently visible on a Challenge? And clicking the challenge opening the results list?

**Comment by veloek** [comment]
Closed by bdc47891e71b14bbafb3e4abf1ddc0da14729066
