### ISSUE TITLE
Feil ved import fra Strava

### ISSUE THREAD

**Issue by roheggda** [veloek/spur#5]
Import failed with error: The instance of entity type 'Athlete' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

**Comment by roheggda** [comment]
Tror kanskje det skjedde noe feil ved kobling til Strava? Jeg fikk ikke noe login - den bare listet en rekke aktiviteter. Gikk deretter til profilen og trykket knappen "Import activities (30d)" - deretter kom feilen.

**Comment by veloek** [comment]
Hmm, det var merkelig oppførsel. Kan ikke huske at du har testet en tidligere versjon av appen heller...

Uansett, prøv den samme knappen igjen nå - tror jeg fikk orden på det. Ref: 02e065af2e215b04480e4d69b80de8b0dd063985

**Comment by roheggda** [comment]
Fungerer fint nå :-)
